; generated by PrusaSlicer 2.7.1+MacOS-arm64 on 2024-01-21 at 14:32:53 UTC


;
; thumbnail begin 160x120 19768
; iVBORw0KGgoAAAANSUhEUgAAAKAAAAB4CAYAAAB1ovlvAAA5r0lEQVR4AaWdV7NtRbXH17dRgngtS8
; tbt4rMQTjgARFQ4jnkKNmEKCqKmMhJJCgmFEUUFSyxtMoHc9V9s8oXv8m6/Cb8tmOPMzrMfR9G7b3W
; mrNn9+h/j9w9N8cee+xWOu6447bvf//7tx/+8Ie3p5xyyvIZOv7440s68cQTFzrhhBMOo1NPPXV70U
; UXbU8//fTtSSedtHMt/1d08sknL8/kb6Szzz57+41vfGP70EMPbc8888zlGmjfvn0lnXPOOdsrr7xy
; uY8+SIzrrLPO2h48eHC7f//+5XOLTjvttO1ll122feGFF7b33nvv8ly+kz7wgQ9sL7jggu3555+//M
; 8Y/Y3/I51xxhkLH6644orl//w7fbn00kuXtqrfbZvrPvKRj2xvueWW7YEDB3b1R6JPEO34XWuMtPfR
; j350uZ5nRF5dd9112+985zvb2267bfnc4jXzwO/0n3Zo1/lh7sTShz70oZ35zPO+EXiRABA3MhD+r8
; BHYxXwBJpgg7Ef/OAHl05VoKuA5yAi2O64446FKVdddVXJDAZ7ySWXbC+++OKFuRl8EmPimnPPPXcX
; 4CKAvvCFLyzgYyLyJEdgnXfeeQvjGR/PzMBhEdBfJ7lHTNKhQ4cWcOXf+O6aa65ZFlYLoBKLjMXD3w
; qkjBcgAz76l4EpzxjbV77yle2TTz65jLUCIv1iYdGOgIzEXPI9ixSe838G4SaDL0o9Vj4dobEo9bix
; B7wMQgZw4YUXLgzIEi6CLw8gSzvaeOKJJxapFFctA2SimUSZ2JNw3AsAkYZxAll03/72t7cPP/zwIk
; lHoAF0TDQSDj7BL75jvEzy1VdfvfzOdzPE/YCHvtEG37GAb7/99uW7UX9ivxgb9/J/XDzXX3/98hvt
; 93gkn5CCP/jBD7aXX375rkXN+FjwtB8lYkXMLc/nHuYqSsNNC3xR0nEjnYHJleRrAS8SHWGiWDV0lv
; bs3Ah4kbjv85///Pa5555bVhWgQQUweSO1mom+IHWQYEjYF198cfvxj398aoIjwVT6AZ/4i1SgT4Jo
; LSExaQMA33jjjc12Rv0EtEpVFidgEsiVZGwRQHvssce2X/3qV5exskhc7C3V3JpP+sL4+PvAAw/sBm
; DL1gMkiH+kQgTgDPCyuqUNBiAAZ0AHxdWnnfKTn/xk+6Uvfam06SrAVaoURqLaUbkAuge0kfRCsgBg
; 2mGiAM4aUnrSJ6Terbfeuvy/BsgZhPTjE5/4xGI7oior8M2AkXbQPK+88soC6jgXPRuxIqQw7Xz5y1
; /+DwBb4BM8AI6OqEpnwRfVrbYa9zNJTJodnQUexCpGJbCSWJWoZYDdA14lIQDxz372s+0Xv/jFZaJZ
; GKzMmYmOwOEeJB5SC2kKj5CGTDhjnAWgthLAo02+o100RwT0LBhR/0g9+kO78rxlP7aASFvwm3ZuuO
; GGxUy58847D5uXEQhpExCjaeAVGnXTAh+Aq9QtoELNMDh+nwGe4MuSjnawU+jYDPC4jtXHhCj1+A4m
; I8VuuummIeggJuFrX/vawgiM+6hKaRvwVECrCOBee+21O96nQGJcOjsz0hDgMrlMTAYtbQjunvSMhN
; rE0WBhRkDqNFTSsgIh92MK8GxByZjRPM8888yyUGaACHi5/sEHH9yl/Tat8Ep2NLK0MxRBh3rAE2wt
; VQuzteEq0OlQ6FHCkFYI4vHHH9/ef//9O6GRynYDFN///veX6/ReI9h0vFjxPeAIVgCspMtE+wAhSs
; NM/3vtZnvLgXcsNihAq66BeB59YtGO+nXzzTcv5gD/V5IRftOnLA0jEPnLdbRjGCqbODwHBwVN0gIh
; /2MC/PjHP17s2YyDzUx4paVudSwYaBXDa9kBVQgFYLCyGFgOn/Abki/H47K0YwI++9nPLtKQycp23K
; c//elF6iExR9INwNAGkqwCFlLBhdMjpA6LAz4xPiSGwDt4yhFLO0i++y962/b+C982bI+24EUEtH0G
; VIyNBTSSkJoceuk5fES/GPvIYUGyIdVY0DmeCJ8eeeSR7be+9a2dUE3GxKancmfsPB0LOkuHZqReS9
; XSDhJDjxZg4/y0GNFSsdzz7LPPLvE82oLZTz311BLTYpJ6wIuTDVhgMBNFXyDux4hWWvl9j2iH65U8
; z529WcakfeZ1CwjfoHx/BqHaAKB5DVIIU4DfZpydGPYRsHzHQoF/AHOknmNsFQn+3e9+d7mfuWRRIR
; 21FVu24YaHM/F8uRZ8UeXSScDDZGcPd9a50OBlhUMwuQqozoRGmAgcFJyMX/ziF9vPfOYzpUMwkjhM
; LuCBoUwwNhSAmgFeJqQeE46t+rGPfWyREPma60972w4YR+3Bb8DyyU9+ckcT5f7PgJFFgbQHxLTTU8
; 09IDI2pB1aBvAJxp6DskHHa8u1wDfjZNAYE2PqpRUjagEve1wxYLoGeBJ9QS28/PLLS4iFsMYs4DIx
; JkDDBDHpGYB87tEDF719kXoAGQ8XMNMOUpAF1rpnBEIWA+PC2YDnFQBnwAgAsc9sJ0rJWSAKwB/+8I
; fbl156afv8888vC2zkoGxUvUhBHr5X8EWxCgNhMAOZBZ7eFUa9WQjaYVDGr0bAk6EA+Ec/+tEiAZlg
; GIydQj6ZtkeAk3gukhjgwUzaAoxIZj6PgAch9WgHOxapBwhph7GiklHB9KkCIiC8/vS3H/Y97aG+6Z
; v3GSbhc0t1ZzAKYsNPfMe8KU1HQW/Bx+/Y3kg+05csMlQy8cceCDdR6mkD8EPL3psJr8TcLBMVc4wV
; 8Ohw9riUeHptTLyprhbw+B27D48LiZWBhj3yve99b5GuMzYbKpdnZwAAHiaOCfc7Jj7SAxe/fXvw5L
; cv1zIZPDNfY8zQYgSA1QIi5MJG6sGPeI32Kf0C0CM7kvEBFvkaJSL3A2jDNT0Q8sxvfvObC3F9VMm0
; TbiL6ATtViDcZJXLj8b51oZXKnXLBBi3q8DHc/C4sEVjCCBLOxgWvbasRszjkjKqPNeotohHkWiHYV
; mFmtsFNDwz/yZxL9chDQWOpNQDXGRGlEwVcR1jR5pFaZjpwYuP2N55wfsWXnFNS+LqoAjQaoGx0I3t
; tdSzDkq18J0XFgKLHRu0F8TGQUE1014G4aZSuQBMD3AmvDKy9RiQ6sLO8Zf2NepbwMvpLlamiX+ZxQ
; B/+tOfLhJuRr3CeNJAhGvMlUJMLJNHn1qAqcCD2cBEGVph0dEOapJncd2IjABAAD+CGilDLO3Ws45Z
; vke6+lsLiLRjnttx8wwkMeaA4aCRnchi1u51HmgTkwYVyxy2bMMoaAA9UQgyITHUtmnZe1Yw6BWtkX
; otdUtncXhcpXxmkDPORWQKbVjtgXhH8qm+e8DLk0QgFZWM/cIko5L4OwJdBR6cDO0wJIO26xpiYnk+
; wGGMtAu4cQ4AelTvEYQtMLIQ1C6ACPDF0E3PVszBbfpEf9AMSD0WcDV3PS+Zdu66664lESAWNr34Hq
; Qatc5ur+CLOWAkVVw5s8CL6oFJee211xZHQ1U6A7qsTpkYQgeoCBbbCGyZVLfwCAAzMS4yANWiXpum
; 3u6+++6dIpB8zQ1vOCdQa6E4Tp6FisQmNhDe4lUPiLRJmRpFBICwZxuOChyIBBAe+9znPvcmAEfOhh
; Oc679mgWdtGasIg5vB5CrgWeDBQAxbVC6hAyRf9v5GoJN4vqGVT33qU0vsCrU5I6kevOSIRerxP+3g
; 7SFh+B/pTr96AOwRkhTbkXaiNKz6gm0IVSA0vGKlNNIw2rWzIGQsaAocDcvNzEuvCdfotHA/f++777
; 7tpge+rHJphBsZxBqpZ+oqF1WiDhhcrkBpBYsBCpIKR8Mkv4FiJs0VPgIe/WEB6Gg4mbSBNMS+8fsK
; IEg9/mq3AV4Wgb+rMfCi+X8WeJZhySvBjTq3sKGSngDwhv1H7PoOyUk7tBkluhXaUUr2gIi2YrETQo
; rzwbyZT54BodXTxpzFxqZXOlWl0gAZA2ECozHZU7lM7IGi1NwKFH43tdXKUpDHpf4PyVCpWRgK0wFC
; 9kojAXqknmGGTFZ6YKdgf0WAIPUOveFk8L/tIPm4BzBmQloAQlR79Xsk+ISq5C+f43NN4zHptBl/z0
; B85ODRi9QzBFbxwDnJ3nQOvmNf46gJtDw/8CBGJiog8pnrrA7P6nizBnxR6hm0NM6XgccgDAdUncoS
; j0nS24rgg/lIpaeffnqn0LOnat0AlFe+YRNsR6tTenYak4jaAYy0hdQTLLTDQtAw75FVyW4ZyL/zHX
; 2CkHa9tpAeAIfnKw0j8ZxnrnvvAsIIzAqE0UHJ0hAbDal3zz33DNN7CpCYT3a+dV7y1ocIwk1WuaMC
; glyfByMATgyvADp3pq1xMmAi95lWwksljwsjRjZeZi7Syw1DhkXMsoxUYZxwgHfvDW/arKp61JE5dE
; E0Ios5Ab/f8T9Sj0mi7RGYIWOGRgEEOW1rhqiOkYgjIDIuFrbePGXyOAjwq2cbZjMJXhm0N24Lv0db
; ADY83HTKGvBFlWvKjMnTXsku+sjJiCEUQEiVM+4+KmwWeFni0RcmBjWptO4BLhNOBn8BCeof21C7ai
; +kgwJQmBzsPYDZu6fql8F9gIi0Z6FGG3THZHjLQclmRmWWYOuRvsS+VjWPHJQ8h7Tl7j3GmYsaKhBu
; aBjkunVyLyEWpR4BYR48o3Jbth6Tw2Q/+uijC/haOddRjM50EpOj5JkBHYTUEwDunkMVsxGKsi5Wew
; 803NMi+kF4xVDUGgBn1Y6ZAM8BoRL0MBBecriDEoHIXzZ5IfXQNACb71oOSg+EPJ85g9+MraqqySDc
; CDCN06piYQQ+AGxC201HdHYEvpy1IC5EQhsbhM/0yaJQ7ZSZ4DCLgcnhXsFmAWlPqjx06ZGL1HPCaQ
; fbDBAzwUgK9o8gKYir9YBWEXzBY3Yjt7nmfN2MOqdPSHX6RBuGa1peN0DM0pD7sa2pnTQAb3YqRhRG
; IOQ77rMe0YLXmE9ugXATpd7+t/YS8NAKfNnZ4DoknvtPfQDfG+ebkXpMNNKFVA1MzOqWVanX1gOeJf
; A6GlnascBMm2XbLUs9wytIvwwQVjjlRsQjGeMIeICE+CKgNYwFca/VNlzTuj/2E36zuKItCbmVU1C2
; pCEEr0jt4WggjbNadsFaE9ADoXa7FeuxztB8sg5KBcJNVrsAyx3/PfA5YF3rrHLNI9KBXngFOwhGUD
; DaCyDrWMCUSp2YkzVZ31Kzhk+MqyH1Ltt35C47jZWMl9sDF+On3pB8KBNAuxXxHEJI8IH2qmt0UPRu
; W6obALubrGVjWszL9Y45gvDmDxy9ZDRev+/cw0JRlYNiPrkCIXNheq+yCRU+9EsHpQnArHJ1oWk4Ao
; +GjbdZLNqy9/RsFekReHyPnYckcQPQyM4zWEy/aE+px8QxOUx2C3h5sgAEUg8mOsm0g4drIDhLsYq4
; nuA45kP+DUnFAvPkhB5ZZ2ipfVbdqNwM0Jb9qcZQ0kv0B8eOhcPCUxr2QEh7hmsEofPA97mooQVCwz
; X0Q225A8CWzWd9IAMBfLrWNDJTvWInVKOsAjpCG9h6pGJM882AT2J1G+BlMZjRmAGe6vayU49apJjV
; ybSDyuW7HuAqYkFgPlDm5S44VJxx0Nl2rDxRxfKZ/5X8Myo62q8sfBYl7ZCj/vnPf74s1J1Y5xvOyY
; 37xyDUFqct+IPUs2h15JhkTCC4dFCgTc/h0MlgkHhbcWdaD3yVvUdHYQThFTwu7LS1wIuBY5iB/dIC
; X0s6WBov0Q7SC6+USZ8BSUVMON4kyXrCNZbcz1J8BpNM6AjVDc/jbz1bM4+X62mHLQlompiRybbhCI
; Rcx6KnTx6t0XJMWlJwf9ivI4g3PfDFglFQq+pbCz6IiUZVISlY0Z4TsxZ8MA/HAAAz6Uy0Wwh7wEPq
; ZZXKeCgPQjIrebK6nAUQ4MVutOoaO8sj3NYSE43KhU/0qZKiM0CkzIw9MSwwz6uJAfSc226BkDbpk/
; Yg/NZr3gsIYx590wMfoNM+M1itQakenwEfgVykHpOj1KMdd+kfKKqNK6ln9Yob1CW+d0XFCeD/hy89
; 6jCpB/OQnNhvUfoYvoHRntowQwLZCmL4hofMgqNffBep1Q79x1vGHPA6vjO3W0nkCoAsdhY61T0eJO
; SC00ExHKUErHLLpi95ft5AxTNMPsyq4vi/wmtTxfm4CHDAhOixeJNGqDGeFvgYJCU8xJm0/6LaNawQ
; i0B7Khf7xbL1St3SZ/cRt6QeE8mCiJ5rBoJbFHlWVrOZUHE6Gvk3vgeEVAF7claL4IMZm0q60l+kUM
; uTdow8k11p1Elmb5nfjfMZBYB/EYCCkN/oE9Iuq+RYQa6DMpKCfs4FC5sMPhpzY3JvPy4PYxAwvgIf
; EsaEdiuPq20B05WGGXwyAkDkIHIrSPvM9e/dXnn6MTsTo3SDWTga2no9qUY7qHk3RGVi7Eg9y5tawM
; JcIL1F1baeaSTtPc+X6UlJY5z0LQOQMeHdAj4kVs82NDxmdc1Dlxy5C4D0g+eYFWkBUEKqwg9+q+oJ
; M/giCDc0YGFBPPinB74o9ZQ8PFyPF0bg5cY8bgW+KPW0fc5/60TVyAhAMHIyZDZSjwmhLVWi4RVVSY
; 8yQGgHYtL9DrWKFPWkgxkizkkGBSPeduif2ytbAM79gyfmk5WG9Ef7Oga6eyBUVdPOY5cds/M9nxEe
; hrlaTkku41JwMTdKQv+2bMEFgGQgrKQwvDIDvqh26RBMpB2AhwHOAGbAF9VuVKP0B8BEo3kEPEIrMY
; TCBOMY4J32vNKeavQATNQ/7WHHmuucBZ+EU0GoBqDgZGi3jp6fwajzxeIkR014Bck+sg0rjfHIoaOX
; cQFq2tOu6zklLRDy13CNdZlDAMIIQIOq5Mt8xt5sUQGeFh4X8absovckX1a5HrBDHG0WfNHJiKEMQE
; P4qOVYjCY8gocJwrGw8mQt+CQmGADCK3Le+fdZEDLRhFZQuabyZhyUzEMC0rSFRDduGT3kHgizKjbU
; hgBxU9bII96YofCgR1bkGvAxUFY1zoYlQZ5zvBZ8rGom2PAFEoPvWuCLTkZkPBILSaWakik6FrOgg+
; gLIGZRaKvqlcZrZsgKau7lL2qTNwC0AN3qI7bnr371q2Vvs0WqtF05KD0Q0tbT171nJ/PjGTGx/D+D
; sCcFnWOzJfCcdnpScBPTbCbZYfhMrA+w4GgQb4oSj05Yr2Yne+Az3QPgoqPB94AJG0zGVaGVGEbhWl
; azmYQc5kAqaru1QCdhpDM2HQ2Jdhg7C83thT1iQgGwtqTf0w/MFeKGxtZ6QKQdHBqkJ3MVx8ZvOg4z
; IHSxP375O3fx3HCNBa8zUjD+n/PF7nW20r0JQKUeD/SgR4POGXw8jHNWSMSzYs4s9uMa68sbYyIAeR
; YT0srjxkoP7CWubUk97sfeUxK0VK37f92X3Jp0JhMzwNKpilgwbvRuXcNzWNCAtXWNxaCYMa3+IDEx
; lcifRymeHRT4bYVSBUKjAdrXVgFlvnssnTWLo1RdVbolLmhTB2UIQFUvRi0bUuIeUG724B+PtmiBL8
; aKuIdVEAehw2EqrQW+HWP54NHb6w68eydZH2N4tMMksvpnHAw3fwP8qEoh2sBT9aiykXRDUgAOj9aI
; UpLvmegeQCUmiGJXKHrXtIl5xNYEPPkZB4X7zSdHXim53QSmDSiPc6TBcI2nNSgNoxCpnJFWYNogeN
; xJt+k5HTAOLxlPi4d58A/SIRck9hwO7oWRFjLAJBgUPa4e+JR6Sjr3utImhjxMnfVsI9iUvlb30D8z
; Gj2wmFCPZNGAGQLAYrvSCIRcA4+xDQko0x5CwJMferZhFcdkERmKsnTfYgupB0D30zCmuCPPNlrecC
; 89J6i5bwHgKORCI6jbP//5z0v1LCCYAV9l9zEAGItK4v8R+GJoJapdGEA7LAxW1azUq0i1RbaCflXS
; qgJcRUwyNiOmgEev9agFRLQCRQ1//etflwrsWQel4gN2J6qdv5U9GAGYQRjnh7bcy2KAuucN9zIj7p
; ikT5tRyIWJRuUSgiClhoEfG54Nt5jQhlhNOZ+bwZfzt4LPPC4mgkHT6HDMgs/JZjVSVYO0QJpq96wl
; xgSA6Q88Y3xM1My9EXwsKDdkEa4xn7wWhAa6GROSOOaTI09x6FoAjCDUbGGcttMC4QiAtk2bmxb4aB
; RnxBo3i0uRhpQbWTo/Az7TWnHnls4AfyMANYor8JnHtfpFz5a2VRGzUs8UGKpSR4P+MdlWTM+Cj0VF
; OxG8Hio0IwklJCceLvzV/uQ7yqmQ9nyeAaEV1lYMuXA9LUEQAr4qNpgB6NzEWK17UNz8PmsH8l30hk
; sA0kk8LsR/vMFGYDYeMKGFnuql46glJjTXoOnym/WIBnEGH0BDolgwWqWnjPM5KT3gAWRSYxa1ZjUL
; c6NjUZEb6eGB0oXvIrEokEBuJm+1xb2AjowG7WWVDLCRitiC/N8DIc+kjRgD1SM2XKMNPQPAPG8xdM
; azfLvByBP2c44HbiL4+JIqZcQ+K7i3kQiGIh2//vWvL53J4IMZrEIkQKxqyXYfnactJA+ebgYgE+Qk
; j9JoPMvdYi3w8Rw8Zldwy8YzZshitOgiEoBHOvE3/5YJPrSkKuNCwsHLKC0r2xBbDtVsQUUEoGEhFs
; 6FqYonh2S4h2ufvOpdZYbEeekBMIbRLNiwtC47IrFs/zAAulsJ5sAI3utAw6MtlAackZJ4ajBYlVsd
; /FOBL9p9DAC7z11o5nLxSrU5ZpwNJpy+xMCuIAN4qCUdjRm1iOQFiPSLtrkXkCPZ/G6GPB0/3uO717
; BBZ50UxoYkxDyiL4zPPlm6XzkkVWX3E1f8186mopEabmVFojTUxIq54d6ekQWA3AgDKBhFte6f2L+b
; 0c1kc5gP0tMqlKqmr9owFAf98MGjFskEM5ksjPnIvBEAI+DclK60QuV6rvMM+CJ4TJ1ZBcMYK6k4Io
; HC2AARmsaA+CwAjTESh8U5pD8sBvo48opzYPrZszZLe3E83LcGgLFkX17RdjydtQtAD2dkwmKUegaA
; Ue0CZNJ4qBLf5NNTvRl8dJqQCwMglEEWAqasBV9OpSGhLbufCau0wAP4UIF4ur5AcC/EQvjNb36zBJ
; wtf7tw0kPO6T2qfHBaiFDw3RoAQtqAhn7QDqrjtQCU4DsLgjbPfmvDWReATDYf9J6yoTiSfmY6PIwI
; qUUpOHbKLPjMdCBJWdEy0AOF9go+xobK0iNdI/UkwGZ4hcWBdGeMJu1ngecZyb/85S8XaUq7TBRSeS
; 0IebbpPdohPef+5L0AkGc4/4Z89gJAwWwFu5ugIggPA2AMvVjPxU1e3JN+Oho8KIddkKxuzBkBkOuf
; v+l/FrDEHC9Mi1XAs3E+DHuA7Et4uDenzGakHgsCR8MS9qhK44trfBVqJq/3uDN4kqUnEy64RwD0et
; rj/zhm0oeoZCTsNAAPHnWYExLLqUYAjCDUAYlakT5ov2sLlgDMxQYyKRuQgo+HMaGGV1qFBqgIKj2w
; eyrwLWr3rfNSYrotG8sa3+5TaYHPPK6FnjmbASj4zd9b4OM6wEq/5UUFMCZKUFe/w3zUI6VT5qor4n
; 5A1VLJBqhNzzmmvPDoDyBHvbsfuAVAwBeD0tkc0pmLZVktJ6SXE7bMTpUcQdgEYCy1V4RKdIiOebRu
; q8zKDsMUQIjRbIGpXi9SxIN/VAcZfBIMBqzGsDL4kFatPG6Wdkh51WAGg+czx/BLS8IJMtpinFEawi
; PUImNXzY4ISW8+OfbXo9xyZU4VD+R7gtZIQ0DdA2CvUNViBPnQCsP0KqSjtlRAWH86BKA5O8/1tcYv
; v8BlBEA3FlHeRWGDDHZPRUwJVdIv237WvVlZYbYAZq/J4/Js2oHBAsCjNJREPeBlYlzwhoVJdfmrr7
; 66LLpKJfcIIPu+X+1E+lXZgr2ANPewACh49bcIwhkAKizce83nteCL2pP7lcz6GpsW+HIZDSEamDyz
; t6MVesFwxgineppORPC11G/leFhAwOT4KoOWt9hzOGAG7QA6xodqNqOxBnwRhEgeYnvWOK4FoJkRVD
; YS3YqaamyjtBztkSggykEw37TcGgBKFjZYtt8rz+/lgvndbBTzOgQgF2kzWeg4qnKuwMdDYQJSwo05
; Bp1H6rcqKkVKYO8RrtHGWAM+CVXJZENRVa4FH1KYVBopMzccefztGhAyFsCLWqdvpvn2AkAI4YFjQp
; wWm1z+5j3TM/lgxuTm9r0C0IiL3ncTgDTkO8Ws8+c7T2vPIrgFQAaDXQZQDHJChEjIvDBxbqWcAaCO
; BtJGMMGYaJzPSj/P7PNoDtoxUzJL3EseF6nHWPweMFtdMwtA7U/HpqlQFbzOAlDVy5yRPaGkjrH2JG
; CWflVljNsn1gAwA5FrNxX4aNi6ryr2B0DiCestADJwj8jNK4xBM0kEr1++681jQEbgo08eGpnzvDHz
; Mcrx8twqjwtAaMe9uiPwAVbUm0UCLQfFzVUtAOq0GOSu+g0PnZNZAFa5c0wWzATCXjMA5HPlBeuk0v
; c1AMz7QnYBkAsYrGczj+r9mEA9pAg+Om7plMHIKvNhpctLd+5bDGb3KWSmwVwkqMZ4r8oFUJhyq8DH
; 7708LuPx8CMLCCrC08SepYJ5xjbUsahCMNigxlN7cUDPCdQbXgtAFzj9ee2eN/f1qA5bDsgoBEP/fG
; NoC4D+rXbGbazPdxtdfOnfTMGpHbBA0TANUqRaTRmAer9MOCvTc1RkWjz4Rya3AGiw1k3WcUJpR/XW
; U4VReumRxvAKbVOY6wn+a1S1mY8ITPrE2Frgy2qXz56UmkHYA2A2cdiQTu6erJVvdKpAOJMFYR51Tr
; LG7IFvAaBMx/6hoZncb3ZA6KjH8yOp3OvRS71V4ReY60GPHtZj1L+X+ahsv5j5UL050T3KwKEdJpz+
; YHti6/EujV4GpEdmMugP/YuLYTYVB3kwJ8C23nA2DRftPxYYDgo5c+sF16bhwAPfcW88rL6XA94BoD
; VkPHwm/dYCIEwgWR/fczYDwMoBoZ3f/va3zVOlRgAUhIDPVyJoW82EQjJofIfc66+/vrNvZC3ZLsCh
; P4BZ4KwFn+PWufPlf9MAvHS3A8LzCY0BxHgOz0wKLtt/FjZMA5AbzOv6/xoA6mh4jJdhG9paKwG1T7
; CJrHsj0Z5PqJoBIBNNbI/J0SOdrWKJwPHVoqhdxohpUTkcI/B5AKYZDb5HsubMxxoAcp8eqVGANUUI
; 2n60w/c4eEQmAPUa6ScZGTFVy7iHZ8PogAAw947m9FtVdq/IxYYxMBmdEI/uZ5AzAKQNnBYYqQ3Id5
; w1EwOpIwBqI7nnt5f5GIGQTAZ5XEJG0ZYDSKzyWfABWCSn8dRW5mMN+LLtpwNmXWCvDjBLwGj30Vdy
; yZzAwL1rAJgxw/0s/gONUxF2AVDVa9CYgRn/ywCkswZJs2iOq0aPmrYqAMqI+AKXKnTAZLMySez3vG
; AA79uaKmmiE5Ftr0wsAsJDGOh6+pn4Xm+6p3LdsGR6L5P9ok+xNKuV2el5vnz2pDMXcZZ+mj298Avf
; 490zfhZND3yjvSDc4ysqhgAUhJbSGGKJ4GNgMBRGzWRB3I5ppewuAL5hDDOJrFyY24sDMimoY9Sym4
; 8iAN1WOSo8NfTBhEcbTMJmxNEwj1vZhNFB0fyIwIPckGRKrgW+SOaT/z+ZDyMHHmWSwSffR8Fn5g+e
; st0Cb9k8cE6/zmQ/+I7+0i9BuHNCaisFR6MaqAzKHW7YMLNZkDggHu6eBTciLRvPixe49NJw2CeEQE
; grMSlMbnXwTy8TotQBOKpF+oejwREYgGZGTWvb6cjpGSNlRxuWLuwUScTMh2Bsqd6W42FdpFpFvqp5
; Rqm3mEwgn+zpDM732vSb23p92zrgWw4pH5XfW1KF1+aLSdYWIcQSrBiG4GTOURFCBiAEI3AKIDMjLZ
; XVA6HAY4UDPEJA1fbKGXvR4zgYl3s01gAv2n38hU8AsXVq1mzQmQlngbCoog04A75o+7HIKS1DNefi
; 0xnwqXa5hvkCT4TbugCkcRhpwt8KhiyKZwHIvTgaTBJMoQw/bjyfBSCThNomB8ubNT2ObS0AAQ7lSj
; gaZDbcJ7wXQp2zGDwKeC34cp8BNAtfx2JG9VYA1KaNrwI7tK9/Hkyr9o/+UOVOTtkq57UApK+E11js
; aIomAHkgq5BJic6HKz6q4RkAmmiXCUg/j7rNErAHQjdeWw+InYKX7MthZkHI2Ih74WwYVrHCeY0U5D
; 76APAMPTDWmO6bkXotm4/fTS8aZpkFX7T9zN+zF5j/10i/XHpPZgoHhYW2BnxgiXgj93nQfQlABuUB
; QjkUQ8dghMWkPS9YyQdgPLdvZwvmW+EXvveAoREAuVajPoZjmCSyE6gIfh+BEDXim9izStaxmNlw7m
; KoJJ5hn1jZshZ8kTzKjrbXgi8SB1LqxO1l95vCiEVGZQ2RidHuN9oj+I7U0/7beVdcPmychplEA9JV
; LNCAsxInFyNIMAv1yHXZ6I2hAPeXtDxh2vGQnaiC8iQBBhwURHw1uUg6HA2u6QHDPK355Ip0NHrZjB
; jny8HmFvB6Dgftubm9Bb4Iwgw++M7xJ+brnZdZ8FWBZ0wXtIivccvgg+eobWy+6P3uvC0zvm7B+Nhs
; JkSVbGFpBCEqDmbBqCobIiMkrjO3GZnJRLc2Xlcg5H7EPBSP1vXgHyTljFrUQXGzUPRSAZS8GrUDKV
; UB61rgVTYfqhTinjXgy46Hp5RxfQRfBOFM0NmjnSl8jZXPCAQcRXgZwbcLgDzclBMPWZsLprPaZtoo
; SD3fK5eN3BYAtVM8wYk+IYEMZLcckgqEEHYKKpmVRxjBU+lnnJNIAN+zXTwPxnfnraHoDChl9wI+JZ
; /84a9B7jXgkzSDovZZm/EAJ9zHvh+dC+KonOxqtVXzjeke7TCzGb1VjGAZFqucVcCk9bzheChiC4RU
; Z/jimpFX3AIh3vvf/va37e9+97s97RuJIGQ1o27WnB9YPYv7TTnuBXiZD9hWbkhfC744R4DQU8pGqr
; flePAZEP79739fQlsx49EEoJ309Vw9APakIE6Lb1TUqYj7CSK1AOhq1Nh2L3CUgC0AZhACYKQeC4KV
; aD65pwIrMOpouBXV0qy1ToVtWxyRD1BaCz5tY3gWbeg1G43itglAx3NYGLHSfRZ83EMWiRANi4xcMm
; Dknhb4OB56pyKaB3lkWS6j7gEQJhCCgLnaDwzEio9q4B5CGUHI/dhVOTMCcwXkDAhZxdgdhFjMiUIA
; h4JXwEhbM0AEICysGOjWATFbMmqnZespDX0BYwt4LfBlb1cb2pMIZsFXxfs83XU24Mz1AA7zxLAL3w
; NIUnmMswLfLgAq+Ricr2jtARDwMWCcDTenxEEAKu0TGLJLAl6y+1xiA65MRBWYlrn5bUd5oggEI/Ww
; PyrJQn9YoeaTWwDxHRr2qbpGxyKeM7gXB4M+EcapXmRYAW8UaqEddy/2wOffVp2f0prrWnYf1wM6wj
; GMpSo2YG4RCNR48l0TgDEcY86OwVVqmO+RejAvBykjWVljqZHMEIAwySBrZmQVnDatFL0/wxOsQF5b
; BVB7diEEUAnFwJQMFA/+GXmsSkPMDusfZwBXqVquN87n93sBn2rXqhjanY31VU6H0pD+RBCCCTQcKh
; ZTJ550kAEI0R5CgTIvxhBfjtTdlmkoIoIPRqE2GOxsXhhGIVUAIpUYhgBUYz2HJBNMjS/5QwoBPLwv
; QD7roKAWkITs47VUPx78s0alwqPnbnzfEuR99NA7FpoBXiY92+rFiiPgVTYf4Ik1mVaqz4AvEv1xLz
; Cf4TlSzSP9WrV+2e7zXERsasC3a1tmBqAq2Q0nDNoUWLYNWgCMIIQhAIRUkCdLRTWxBoTcx/3s6vr1
; r3+9eLs9u7AHRDxb8sl4bb48O5Oggq4+/R3b5z+4Oew7AewBndp1I9Bldcu1xvmsrpmRei17j374vp
; C9gE/BQ7ssTmxoTtHVYZ0Fn0T/uZ+EANpsk8VmFY4BdJQ/WQ3TC8n0QGgJlvZcZSzPgBC7AuOWOB/q
; ctZByWB89LJ3bJ+6+t3bF+44YfvAbectwHrs8mN2AQuaUaeQr0OwvnGmH60wEw6ZacU1Ui/be7ZpJb
; h1fWvABwFibD3MFkDNd2vBh9TjPuaeNChzODycCIbSeb1bD6LMnR2pYlT3chD5oaN3HBTf4jMDQoFI
; gBlHw2MmdFBsC2ZTZbPQoTcJYPk/dPXpR2+vPeOdywQb6Iapvv9OW2wtMcHRsWi9iLpl36lqlXqAT4
; k6Al4FvmzzudXUrNWs5COYj/2mT8Bfj2Fuga8CoNqU9nlJ+lIP2HoVKxfjaMAEDU/+WpgKo3sgFHx0
; lsnA5uPeBy85Ykclaz/B8IqpkeFM7it3n7F9/b5zF6mFLXnVaUct4OJ/VPvN57xne83+Y4bBa085rd
; 4tgkTFQWGFzqjOFjE2Xx0xAp3Aq2w9vqOfHiY+I/V6Dgf3WxhcFZZG8GHjkcclnJLzvP5On/jcAx+/
; 47RAfAZ80ia/GYmLlVZ0vApM66bTgTiALAU9LZ+JZLCCL2ZIYDCntT955bsWqUWQ+sr3H7kAi/+pmr
; ntvP/ePnj7+YvXVU1SdFCsAq4mXQcGFdkDF/ejblj11aGYs6qVv24WymZCHkf+nCVedL7WSL3K3uOv
; bz3KWy6cXxYox+nFgwoqmw8+Mkbuq8CnJ02/UMERfPv27Tv8iF69wKjjW4FpGOM+4AhCHorq8LhfB/
; /gxUcswAKI0hWnHrnDYOvyXOVMCuU+bIvU855xUBiwWQYnG1DhRAGo2fQeK5/NUPHc6rUqVeC7cb+3
; gCqzI0o8VR/j2yv4Ilkj6Pwxp8w9DhmFulyTgVfZfJZn8QwByG8KKf6vwLcAEAb6nhCP0m15xFVgmo
; d6mCIdZtI9xTSuuFbNYEzVwVRWk28Axx5DCtFmyy5sARFGqvphMkZ9jB/OEpNNpQdVNG48mgFdpV7z
; a1RpZwZ4mZSG3C/fesDr2Xt8ducf84/kR2tVUq/ncEDawJpp9M94XwW+HQCy79Xsx8gjbmVHTP4DHD
; MjM55xVbCA/eV+3FkHpQIiE44UQ6o76YJhDXEvFTVIQ99dMgJcz0xAJVcSfQS8XMXiGyfXSL3K3qPP
; 7L8mfRlTsWvAp9RjwaMx6N8IfAsAUUuWkSv9enHBCoQwx1iTecQ88BkQch+BYSbaIGrezjkLRN8Uab
; 1ir/x/BEwAaOCcUnRihxHQs0TfHBN/8ytUZ4AXAajn7Vvp9wI+87h4utyDNNTbXQM+nRIkKdew+OlT
; dDoy+E455ZTtRuORh2hQrgEh13uauiKdifbIrlkQshB4lQErMTLZd3NUQesKiIzBN146uTFcEwteZy
; hfy9g86NHJmrXp8ncXvrU3xTTlrGebbT1tOQtCZoDHfeRxLRiNc+p2U64dgQ+iv76MPKbZDLdxXwW+
; BYDxbZlcaMyOjvdAyO88VNsvFysY82ECeyDkOgxeshG0V9mFMNaq5J409EDIePh5JlapDspaCRbJc1
; SQHD07bqRi4Y8lWrMhlUrdco1xvgjCCnzwB5OCxe7Wi6x2xQF/W+DjOuO5fI7gU+rxPc8z9hfBdxgA
; JTrpfo8KhEgTJUwuVMh7R3i4r2jPIARwqDRSMzFPWdmGGvGoQp4bJ5HPZiGUlD0AGK6xnq5lS46ARF
; 8IVdB/vfc1Nl0kU2b0fw3wsrql39b0VeEV87gIh9YmIqWe8TsrXSJGeKYCJgKvsvn4a6SB30sAZhAa
; jNY5UfLxWUDNFK5yHe0AEBgq+MhkEF5B9fbswghEA9IeVqlHiFFvNe+MmpaQhL5Xt1KRM8Q9VIRgwC
; N9Bdxe7Dq9biZ9LfByFQuLw3e5eDQGuwGx9/h9BL5I9BcNRFt8hucCeAS+SAKav4Dv5JNP3g3A1pvT
; zVb4HjE73fOMMxAZtGeWkIhmFdJWZReOgMhKoi1sOiZd11+VvYZi5XVPdY+kGlIHEFJ2RL+ylO6p1y
; jtuM5deZZTzQCvCq/AJxYZ/SGchQe/BnhZIOE0aUfHmr4Z8Cnx+B9pr0DZcGMLgILQ4ks6kDu+BoSE
; adiPyyZymN1zTnpARFIg9dxpZjysohEAYUI8e7kCzizBWBYXatno/wzoKqJP2qprgJfzuL6NAA20V/
; BBOjpWunNPBbwe+CIIPZfnMABGEOqmw1hPS2AgpuhaIMxAZJI52erFF19cGAtjLH0aeclVRY1l7Ewg
; bbgrbEbKVKBUohm0bhVI9NSptij/Y1Yw6exHyX1qAS5LeR0Lj+Cd8W4j+OAzxRWe5QKfojk1CzyLT+
; GxjgbfaYbNSj7JmlLuXeKAojiD0BIeGBJzxTTgcWMzcUKkJsl9Mgmxiob/Pf52JmbIRJrcr8IQFrwK
; glkQVnZYDI3MtpW/Q3160KNHmbQoLrIqb0ufUMkslBHw+J0FgBQGJHE+9Gzp7wz4GIepukrlmlky1j
; cCH4tA9U0/sZ03sUGj2XScCaXTWR3Hjez59MsIQr7nAYRXmNDWxia9NplbAdEYHn1qScYYrtEmbGVa
; ZoixsTjo1+w9Fbh8SxGg6DkTPRUL0b7z0qrZY/ycCsFij05iLrFzq2kEYbb33BPC/z17jz7oWLTAR5
; u+/pXP3MPi/OMf/7gbgDDHqLoR7somjDvpDOzGQTI4nAzK5HnorINiTFHSm3PjU2/iBCN98SQv7qlA
; OKMCVe+eo1IBekadas9RfElhBQtuDfCyY0FfDPJHXrJAsT+xjVt2Xgyv0H8WGO3G+eUZHoQ0cjSUen
; wPv2mT7yL49KD1fE866aTlHnjyl7/8Zbuh5o8f3f9Bx3uecVXAaoqJe9kozTvTyAfOOCgCMXptTBpt
; Wow5o6KzuvaAIEMrFYhm7THL42N4ZaROM9EOHjJ7IjzQ3bDUjG0XpR33eU4OfUHKchQJ/esBL6tb47
; 3wne80u3jWLPgi0S/4Ttv8bkEu/zMXjJ8MEiaZQfANHUdaoQbjQ0cgzEBEZFM1gvHN/7MOSgYiDMUj
; ZWHAkKrOcAaMSkNLsyrJswaIMJYwRmUGzJB9RZqzSR7nIEYCWqDLajbaeoSgmDs83VngZXXr3Hm8XM
; 5oVMDr2XtgRQ+XPvIdRb5/+tOflowXxSHEgP/5z39u//Wvf203vooVOwXxnW3CGRAi/rH1PFdZ+2KN
; p2x+Mp4N42kNBw60S/97gFQVa/MA7r2ABzK57qFAe7XlzC+TPcFByTZdD3RWptMOk4qjAY8M8q8BXs
; zjomncPsu41ki9HF7x3Bv6SaCZZ7B3BxOEcaGCIX4Dcxs9GAbFgFyZLRDmMA2ilBMHsBuifcFnJmIE
; QoHIpLiXNUpDd+RVkzQCoBKGv3pgqIQReEbERJl5mVkQLfXKwndj1Qh0EpPLzjQWuyEV7o2RiRngaX
; Y5b8w13zMPtLUWfLQHT+CtWQ4IvKAZefEQcwv4TjzxxOUv9vXGXB3EQ7EnOLuXVdUDIZOAPUOsyYqa
; OGi9Ix7ak4ZehwmQDWsLXs0B99TUSDrSjtUZvo5qBJYcLM+SjD5XxRaV1G71GYmBXYR6on8t4PEZDc
; Xc8NxK3bIgYl1nBTzmDl54oFFWt+7XtRS/Al4GH7zgep4p8KKkQx3j8fL2AcZA/8AFldcbG4xIhykU
; CeBIxIi30g9Hg6AyttrIQaFzVQBUSembgs4cFLxagMk9OZSTAdgDJqBi8DooPcDOSDRr4GKMswe+lu
; 2LXYSaMtsUCZCzHZIysKxVsrRzQXNPBh6/u7OR5/ZsPe5xS0MLeNzj9lp+y+CLxLgQWL///e+3//73
; v7evvvrqmyo4Np47gKhnIxCAtL4Lu4UVCxBmHRQmwa2FSkC3HJpVaannCEZDGu5LzV70SEJGUMA0z+
; iL4BF4s21BTioSaNaWq6Sc708GjMZXWXQAz2hFy76LEs+FDzj4njmiPd/UmT3clpOhaWbwOIKPuWDx
; aeu1wIe6lSxI0FtfMiFZtOaOuCeCGBbuM/tyK5U8AiIPdNe/r/GqPLceEFXZtGOtmvZhL87YIqWhJ0
; q5Z3Ut6ZXGMwhnQZeJdlDHxPQIKrPYAfgM8DLRN4PXjC07GDN2HsQzPC2Lzy5c7u9JvQg+6YQTTlh+
; s28bvZcWCBk44PvHP/6xSD+k2IyDUgERcU4el1o8mFEVu846LUhBt1eOpEyPVKPuWOPzXtsyoO7xJS
; OwtQLGSByckz/84Q+7jjybAV3ej0tfPEk1Sr41oRWI3wEd/UGCRUdjFngSbXkowCa60Jl0NDAWGRzV
; LHzmxl64JgMRJrMKkVoCyPBIq+q6B0ZAYmbEQyTjZK8BDROjbehRupUzNEvmXJE4OhUjwMU0mQWjFm
; 2wR4bUGm3NgE5iDPbB3Ctt8pwZqVflcQEzY7PMfo3Ukywepk983uQ4jqkVvGHCK6jM2FmkBNslUcWI
; 0R4IIyMYQA4DZK9tBMaWBLG6BubMSBxBmlU3k2QYgjZnJVjrOkuXtOd6hJplNyClalwf+YHTx8LHmx
; wBj+s1UaIDydwZdAaUs8CjTe13HQ3+Wow7Cz7us1Kba48//viFNvmBXEAOF8MXxlZ2IZ3CPmF1In0q
; aajHBTAM07TsFKtYWjZOBF9rAjWW8wablh3ZA5PVLB4/MgvqVmhEe7XlvTIx8By11FKxjAvJ6Hl8GX
; ge/OO5hi1Vy3cG6fm/BTwIPpjHrcIr2oa025N68JCYH9fzWfAdBkC2MZJKIzBarY48GFYGaSVSVDGF
; IyPo3IydyACRPPFtipVEnJGQALmq0vH3WanG/fRJlZwB1lsM1XM9PIn/HQegZHOTRRsjFUtbLHwqSW
; JVMn8N2tPvyr7LEo/na35k4Jm7NY/bczLUirSTwcf/1mrSbgTeDgBlNgFlDF8msGcXVk4K0pJdVpaQ
; W63RU80VELVTuFfbsef9tdQ298d31M5I0BZwlIZuwNJJad3T6yP9sbiCieHgH0yZSuL1+GZkgjit9r
; QSbca5UOJxvWVsqlfDNfyd9XD5DK/MdAA++onJQDtZ6kHHHXfcQhukHieMklLLpTQ9IOZB4h2xyYjE
; eJXQngUjA/GA8Gx4zwAxhn08CUvje6+kNIzpxTV9iQDjftKdaA6kzCzoqmwFhSSkT2lnDfAy6XlDAJ
; nnrQ2tKA094wde8bmSeoJvASCxPVaUBQRVB0dAhBmoXNogmk8gVQm4FoiqUQOpPftxBEpTRJ4OuhY0
; En2w0hq7UHtuBLZM3IsKJcAfc7ezoJNoi8XF2CxKILTVAl0LeIZS6DMY8OCm2dBKtvVoj37Ab4CYJV
; 8E3g4ARTvknlr1/giEMMNJhikauaSNCKQCSr+bAWOWBIZvclpphqKtxf++z20t+DLQ9JS152b7gxGO
; 7WbZm9kJVfIIdKpXFzt8V9LxP22jxejvCHgxc+H+ZsbGZ3nFvbOhFYhFSXiOsfKZ/qLJtP0q8C0AjF
; 4NxABYnTTUk4YGOZmISioyCNQMsUMG1wOi4GupZqtqaadlP2anppKUVgGPpGq8pwVu9yQDnp7jwMRg
; 5xHEBzzVGD0RtTJdYuRBB8tYXhYGmD9kTgDUCHjcb/Qhgg2iLSMAI+DxnQeW0m6UeLRlerIC37HHHv
; sfAEYg0lkPGNI4jRLQcqu82jLBUIKoxLZYDTkcECXgSDoCGuvVWiqrp/4k2qmS9WspSkOYHBeHhHSj
; 7o887kjCMS76BbizLQeffdXFSM2iMVDJxA616SPwIJ09ntVStzokAMvvMvgYM44G7bQcDb7XZOD/CD
; 7o/wAGJx3YGfQD/AAAAABJRU5ErkJggg==
; thumbnail end
;
; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R0
M73 Q0 S0
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm / sec
M204 S1250 T1250 ; sets acceleration (S) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec

; printing object Recorregut1.stl id:0 copy 0
; stop printing object Recorregut1.stl id:0 copy 0

;TYPE:Custom
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.13.2 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 X73.0231 Y67.8592 W104.003 H74.2834 ; mesh bed levelling

G1 Z0.2 F720
G1 Y-3 F1000 ; go outside print area
G92 E0
G1 X60 E9 F1000 ; intro line
G1 X100 E12.5 F1000 ; intro line
M73 P9 R0
M73 Q9 S0

G92 E0
M221 S95

; Don't change E values below. Excessive value can damage the printer.
M907 E430 ; set extruder motor current
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K0.05 ; Filament gcode LA 1.5
M900 K30 ; Filament gcode LA 1.0

M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


G1 E-.8 F2100
M73 P15 R0
M73 Q15 S0
G1 Z.2 F720
;AFTER_LAYER_CHANGE
;0.2
G1 X79.482 Y106.224 F10800
G1 Z.2 F720
M73 P17 R0
M73 Q18 S0
G1 E.8 F2100
M204 S800
;TYPE:Skirt/Brim
;WIDTH:0.42
G1 F1200
G1 X110.33 Y83.142 E1.20801
G1 X137.65 Y68.329 E.97441
M73 P22 R0
M73 Q22 S0
G1 X138.986 Y68.051 E.04279
M73 P26 R0
M73 Q26 S0
G1 X140.319 Y68.607 E.04529
G1 X175.999 Y98.884 E1.46722
M73 Q27 S0
G1 X176.838 Y100.697 E.06264
M73 P32 R0
M73 Q32 S0
G1 X176.838 Y136.299 E1.11628
G1 X176.446 Y137.606 E.04278
M73 P36 R0
M73 Q37 S0
G1 X175.4 Y138.483 E.0428
G1 X174.585 Y138.673 E.02624
M73 P37 R0
G1 X111.993 Y141.954 E1.96522
G1 X110.436 Y141.477 E.05106
M73 P44 R0
M73 Q45 S0
G1 X74.107 Y114.04 E1.42742
M73 P45 R0
G1 X73.3 Y112.939 E.0428
M73 P50 R0
M73 Q51 S0
G1 X73.231 Y111.577 E.04276
G1 X74.115 Y110.239 E.05028
M73 P51 R0
G1 X79.434 Y106.26 E.20827
M204 S1000
; printing object Recorregut1.stl id:0 copy 0
;WIPE_START
G1 F8640
M73 P52 R0
M73 Q52 S0
G1 X79.482 Y106.224 E-.01385
G1 X82.208 Y104.184 E-.78615
;WIPE_END
G1 Z.6 F720
G1 X139.05 Y70.91 F10800
G1 Z.2 F720
M73 P53 R0
M73 Q54 S0
G1 E.8 F2100
M73 P54 R0
M204 S800
;TYPE:External perimeter
;WIDTH:0.399998
G1 F1200
G1 X174.198 Y100.736 E1.36869
;WIDTH:0.417318
G1 X174.252 Y100.793 E.00244
M73 P59 R0
M73 Q60 S0
G1 X174.261 Y100.872 E.00248
;WIDTH:0.399996
G1 X174.261 Y135.94 E1.0412
;WIDTH:0.428413
G1 X174.246 Y136.011 E.00233
M73 P64 R0
M73 Q64 S0
;WIDTH:0.45683
G1 X174.232 Y136.083 E.00252
G1 X174.162 Y136.101 E.00249
;WIDTH:0.428412
G1 X174.091 Y136.119 E.00235
;WIDTH:0.4
G1 X111.996 Y139.374 E1.84621
G1 X111.879 Y139.338 E.00363
M73 P71 R0
M73 Q72 S0
G1 X76.062 Y112.287 E1.33268
;WIDTH:0.444508
G1 X76.004 Y112.215 E.00309
M73 P77 R0
M73 Q77 S0
;WIDTH:0.489018
G1 X75.946 Y112.144 E.0034
G1 X76.004 Y112.072 E.00343
;WIDTH:0.444508
G1 X76.062 Y112.001 E.00306
;WIDTH:0.399998
G1 X111.456 Y85.518 E1.3125
M204 S1000
; stop printing object Recorregut1.stl id:0 copy 0
;WIPE_START
G1 F8640;_WIPE
M73 P82 R0
M73 Q83 S0
G1 X108.682 Y87.594 E-.8
;WIPE_END
M107
;TYPE:Custom
; Filament-specific end gcode
G1 Z1.2 F720 ; Move print head up
M73 P83 R0
G1 X0 Y200 F3600 ; park
G1 Z49.2 F720 ; Move print head further up
M73 P90 R0
M73 Q90 S0
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA
M907 E538 ; reset extruder motor current
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
M84 ; disable motors
; max_layer_z = 0.2
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 37.25
; filament used [cm3] = 0.09
; filament used [g] = 0.11
; filament cost = 0.00
; total filament used [g] = 0.11
; total filament cost = 0.00
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 41s
; estimated printing time (silent mode) = 41s
; estimated first layer printing time (normal mode) = 41s
; estimated first layer printing time (silent mode) = 41s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; color_change_gcode = M600\nG1 E0.4 F1500 ; prime after color change
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"nozzle_diameter[0]!=0.8 and printer_notes!~/.*PG.*/ and ! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material) and printer_notes!~/.*MINIIS.*/"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 1
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = {if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+1, max_print_height)} F720 ; Move print head up{endif}\nG1 X0 Y200 F3600 ; park\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+49, max_print_height)} F720 ; Move print head further up{endif}\nG4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\nM84 ; disable motors\n; max_layer_z = [max_layer_z]
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 25
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 100
; filament_colour = #FF8000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 27.82
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = "Prusa PLA"
; filament_soluble = 0
; filament_spool_weight = 230
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = Made for Prusa
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 4
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = octoprint
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = prusalink
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_overlap = 10%
; infill_speed = 80
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0.25
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 100
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 15
; min_skirt_length = 4
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{printing_filament_types}_{printer_model}_{print_time}.gcode
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 45
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.20mm QUALITY @MK3
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = Original Prusa i3 MK3S & MK3S+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 1
; retract_before_wipe = 0%
; retract_layer_change = 1
; retract_length = 0.8
; retract_length_toolchange = 4
; retract_lift = 0.4
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 35
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 10
; small_perimeter_speed = 25
; solid_infill_acceleration = 0
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.8}0.06{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif nozzle_diameter[0]==0.8}0.01{elsif nozzle_diameter[0]==0.6}0.04{else}0.05{endif} ; Filament gcode LA 1.5\n{if printer_notes=~/.*PRINTER_MODEL_MINI.*/};{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}M900 K200{elsif nozzle_diameter[0]==0.6}M900 K18{elsif nozzle_diameter[0]==0.8};{else}M900 K30{endif} ; Filament gcode LA 1.0\n\n{if printer_notes=~/.*PRINTER_MODEL_MINIIS.*/}\nM572 S{if nozzle_diameter[0]==0.6}0.17{elsif nozzle_diameter[0]==0.8}0.12{elsif nozzle_diameter[0]==0.4}0.3{elsif nozzle_diameter[0]==0.25}0.85{else}0{endif}\n{endif}"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.13.2 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 X{first_layer_print_min[0]} Y{first_layer_print_min[1]} W{(first_layer_print_max[0]) - (first_layer_print_min[0])} H{(first_layer_print_max[1]) - (first_layer_print_min[1])} ; mesh bed levelling\n{if filament_settings_id[initial_tool]=~/.*Prusament PA11.*/}\nG1 Z0.3 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E9 F1000 ; intro line\n{else}\nG1 Z0.2 F720\nG1 Y-3 F1000 ; go outside print area\nG92 E0\nG1 X60 E9 F1000 ; intro line\nG1 X100 E12.5 F1000 ; intro line\n{endif}\nG92 E0\nM221 S{if layer_height<0.075}100{else}95{endif}\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; support_tree_angle = 40
; support_tree_angle_slow = 30
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 3
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.6
; support_tree_top_rate = 30%
; temperature = 210
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; thumbnails = 160x120
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotoniclines
; top_infill_extrusion_width = 0.4
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 40
; top_solid_layers = 5
; top_solid_min_thickness = 0.7
; travel_acceleration = 0
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_slope = 0
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
